#!/bin/sh

output='{ "message": "Hello, world!" }'

echo >&2 'Super-complex enterprise server application initialising...'
sleep 1
echo >&2 'Still going...'
sleep 1
echo >&2 'Server initialised.'

INT=0
while true; do
    INT=$(expr 1 + $INT)
    echo -e "HTTP/1.1 200 OK\\r\\n\\r\\n$INT Ladybirds found" | nc -l -p 8080
done
